### ISSUE TITLE
Camera Moving

### ISSUE THREAD

**Issue by Kimsumi111** [Kimsumi111/Portfolio_Angrybird#1]
---
name: Camera Moving
about: Camera move with cinemachine
title: ''Portfolio_Angrybird"
labels: enhancement
assignees: Kimsumi111

---

## Description
What to do.

## Tasks
- [x] 캐릭터에 애니메이션 연결
- [x] 측면 카메라, 캐릭터 따라다니는 카메라 배치
- [x] 두 카메라의 전환 구현
