### ISSUE TITLE
Refactory & card UI

### ISSUE THREAD

**Issue by Kimsumi111** [Kimsumi111/Portfolio_Angrybird#4]
---
name: Refactory & UI
about: object pool and card
title: ''Portfolio_Angrybird"
labels: enhancement
assignees: Kimsumi111

---

## Description
What to do.

## Tasks
- [x] 플레이어 오브젝트 풀로 생성하기
- [x] 캐릭터 갯수 제한하기
- [x] 카드 UI 구현하기
