### ISSUE TITLE
Last Dance

### ISSUE THREAD

**Issue by Kimsumi111** [Kimsumi111/Portfolio_Angrybird#5]
---
name: Refactory & UI
about: object pool and card
title: ''Portfolio_Angrybird"
labels: enhancement
assignees: Kimsumi111

---

## Description
What to do.

## Tasks
- [x] 블루 능력 만들기
- [x] 보스 스테이지 구현
- [x] 스테이지 1 적 다 죽이면 점수에 따른 이펙트
- [x] 스테이지 1 이펙트 후 보스 스테이지 이동
- [x] 시작 페이지 만들기
- [x] 스테이지 고르는 페이지 만들기
- [x] 레드 능력 만들기
- [x] 노랑 능력 만들기
